version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
      - ./data.json:/data/data.json:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
    command: ["go", "run", "main.go"]
    stdin_open: true
    tty: true